### ISSUE TITLE
Login with api key on github actions

### ISSUE THREAD

**Issue by MKlimentowicz** [stripe/stripe-cli#1053]
I want to forward stripe webhooks to a local address in my automated tests in a github action. Unfortunately the interactive login with api key does not work.

### Issue
I get this error `Enter your API key: inappropriate ioctl for device` 
when I try to execute this `stripe login --interactive --api-key ${{ secrets.STRIPE_TEST_API_KEY }}`

### Expected Behavior
Successful login

### Steps to reproduce
Docs: https://stripe.com/docs/stripe-cli#install   (apt)
```
name: bla bla bla
on:
  push:
    branches: [develop]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install stripe cli
        run: |
          curl -s https://packages.stripe.dev/api/security/keypair/stripe-cli-gpg/public | gpg --dearmor | sudo tee /usr/share/keyrings/stripe.gpg
          echo "deb [signed-by=/usr/share/keyrings/stripe.gpg] https://packages.stripe.dev/stripe-cli-debian-local stable main" | sudo tee -a /etc/apt/sources.list.d/stripe.list
          sudo apt update          
          sudo apt install stripe
          stripe login --interactive --api-key ${{ secrets.STRIPE_TEST_API_KEY }}
```

### Traceback
`Enter your API key: inappropriate ioctl for device`

### Environment
Github Actions - Linux - Ubuntu latest
