### ISSUE TITLE
Platform listener always receives both direct events and connect account events in webhook

### ISSUE THREAD

**Issue by nerder** [stripe/stripe-cli#1127]
### Issue

From my testing it seems like that when an event is triggered from the connected account, and a listener for a platform is present, that listener will be invoked as well. 

### Expected Behavior

Only the connected webhook listener is to be called, as in the actual live environment.

### Steps to reproduce

1. Create 2 endpoints, one for connected events and one for platform events
2. Setup 2 listener with the same event for both webhook endpoint
3. Fire that event from the connected account

### Traceback
_Share any debug output that was given by the CLI_

### Environment
macOS
stripe-cli: latest

**Comment by etsai-stripe** [comment]
@nerder could you please list out the CLI commands you used to create those endpoints?

**Comment by nerder** [comment]
I'm using the docker containers, so in my docker compose I have this:

```yml
  stripe-cli-connected:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli-connected
    command: >
      listen
      --device-name ${DEVICE_NAME}-connected
      --events=customer.created,customer.deleted,customer.updated,customer.subscription.created,customer.subscription.updated,customer.subscription.deleted,payment_method.attached,payment_method.detached,invoice.paid
      --forward-connect-to http://localshost:5001/connected/stripe-connected
    environment:
      - STRIPE_API_KEY
      - DEVICE_NAME
  stripe-cli-platform:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli-platform
    command: >
      listen 
      --device-name ${DEVICE_NAME}-platform
      --events=customer.created,customer.deleted,customer.updated,payment_method.attached,payment_method.updated,payment_method.detached
      --forward-to http://localshost:5001/checkin-test-fba3d/us-central1/platform/stripe-platform
    environment:
      - STRIPE_API_KEY
      - DEVICE_NAME
```
