### ISSUE TITLE
Webhook call filed when run stripe-cli in docker

### ISSUE THREAD

**Issue by ilyavas** [stripe/stripe-cli#427]
### Issue
I run stripe-cli in docker. When event is triggered, the listener displays that new event was received, but attempt to call webhook leads to error:

2020-04-19 04:38:18   --> payment_intent.created [evt_1GaklHJZOtDDNS67aUxBiuZG]
2020-04-19 04:38:18            [ERROR] Failed to POST: Post "https://localhost/fm/StripeWebhooks/ChargeSucceeded": dial tcp [::1]:443: connect: connection refused

The application is running and endpoint is available through browser or fiddler.

### Expected Behavior
Webhook is called without error.

### Steps to reproduce
Just checkout last stripe/stripe-cli Image, run the command suggested by doc:
docker run --rm -it stripe/stripe-cli --api-key my-secret-stripe-key listen --forward-to=https://localhost/fm/StripeWebhooks/ChargeSucceeded

### Environment
Windows

**Comment by Stone624** [comment]
Hello, did you find a solution to this? I'm stuck on this same problem. My application is working fine from the browser request but Stripe CLI can't connect. The application (from Docker-compose activity) doesn't show an incoming request at all, so I suspect it's something regarding docker's networking (Cli is its own container outside of any network). I've been trying various things but no luck yet.

**Comment by Stone624** [comment]
Spoke too soon. The next thing I searched and tried worked. Solution for me was to add `--network="host"` to the docker run command.

My full docker command for this:
```
docker run --network="host" --rm -it stripe/stripe-cli listen --forward-to https://localhost/stripe/webhook --skip-verify \
    --api-key sk_test_key
```

NOTE : Without "--skip-verify" the post will fail with "x509: certificate signed by unknown authority" 

ALSO : Remember to set the Stripe Webhook signing secret given by the "Listen" command to your application's environment variable.

Triggering is the same way :
```
docker run --rm -it stripe/stripe-cli trigger payment_intent.created \
    --api-key sk_test_key
```

Found solution here:
https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach

Hope this helps somebody who needs it !

**Comment by namamono123** [comment]
> Spoke too soon. The next thing I searched and tried worked. Solution for me was to add `--network="host"` to the docker run command.
> 
> My full docker command for this:
> 
> ```
> docker run --network="host" --rm -it stripe/stripe-cli listen --forward-to https://localhost/stripe/webhook --skip-verify \
>     --api-key sk_test_key
> ```
> 
> NOTE : Without "--skip-verify" the post will fail with "x509: certificate signed by unknown authority"
> 
> ALSO : Remember to set the Stripe Webhook signing secret given by the "Listen" command to your application's environment variable.
> 
> Triggering is the same way :
> 
> ```
> docker run --rm -it stripe/stripe-cli trigger payment_intent.created \
>     --api-key sk_test_key
> ```
> 
> Found solution here:
> https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach
> 
> Hope this helps somebody who needs it !

So appreciated!
I struggled due to the same problem for a few days, but finally solved thanks to your advice!

**Comment by maraerben** [comment]
If you use Stripe image as part of Docker Compose environment, it is necessary to set `network_mode` as `host`.

Following docker-compose.yaml set up works for me:

```yaml
...
stripe:
    image: "stripe/stripe-cli:latest"
    network_mode: host
    environment:
        STRIPE_API_KEY: ${STRIPE_SECRET_API_KEY}
        STRIPE_DEVICE_NAME: ${STRIPE_DEVICE_NAME}
    command:
        listen --forward-to localhost:8000/api/stripe/webhook
...
```

**Comment by gabriel-rcpereira** [comment]
I'm on MacOS, the solution described above worked only between two docker instances but doesn't when the application is running outside of a docker container. What worked for me:

```
  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe_cli
    environment:
      STRIPE_API_KEY: ${STRIPE_APIKEY}
    command: "listen --forward-to host.docker.internal:8086/webhook"

```
