### ISSUE TITLE
Installing stripe-cli in automation fails with signature errors because bintray.com is returning 403

### ISSUE THREAD

**Issue by khuey** [stripe/stripe-cli#628]
```Executing: /tmp/apt-key-gpghome.OvFQrIx9Nt/gpg.1.sh --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys 379CE192D401AB61
gpg: key 379CE192D401AB61: 1 signature not checked due to a missing key
gpg: key 379CE192D401AB61: public key "Bintray (by JFrog) <bintray@bintray.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
deb https://dl.bintray.com/stripe/stripe-cli-deb stable main
E: Failed to fetch https://dl.bintray.com/stripe/stripe-cli-deb/dists/stable/InRelease  403  Forbidden [IP: 34.214.135.19 443]
E: The repository 'https://dl.bintray.com/stripe/stripe-cli-deb stable InRelease' is not signed.
```

The big warning message on bintray.com about it shutting down on May 1st is not encouraging either.

**Comment by tomer-stripe** [comment]
Hey @khuey! Unfortunately Bintray is sunsetting the product and we haven't been able to find an alternative service that's going to be easy for us to adopt :(

**Comment by khuey** [comment]
Might be a good idea to remove the "apt-get"/"yum" sections in docs about installing stripe-cli then.

I switched to downloading the deb from Github and installing it from dpkg.

**Comment by tomer-stripe** [comment]
Yep! We'll get that removed.

**Comment by ianjabour-stripe** [comment]
Documentation has been updated to not include deprecated "apt-get" or "yum" instructions.

**Comment by carlalexander** [comment]
For anyone who used the old package to run Stripe CLI on GitHub actions, you can install it this way now:

```yml
jobs:
  stripe-cli-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Install Stripe CLI
        run: wget https://github.com/stripe/stripe-cli/releases/download/v1.6.4/stripe_1.6.4_linux_x86_64.tar.gz -O - | tar -xzvf - -C /usr/local/bin
```
