### ISSUE TITLE
Create a Github Action 

### ISSUE THREAD

**Issue by GrandSchtroumpf** [stripe/stripe-cli#699]
### Problem
I would like to run stripe cli in a Github Action environment. My project is not using Docker, therefore I cannot use the docker image.

### Feature
Create an action to run Stripe on Github Action with [composite run step](https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action)
Publish it to [Github Marketplace](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace)

### Examples
```yml
- name: Setup Stripe CLI
  uses: stripe/action
  env:
    STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
    STRIPE_DEVICE_NAME: ${{ secrets.STRIPE_DEVICE_NAME }}
```
