### ISSUE TITLE
v1.7.9 exited with code 0 using docker compose

### ISSUE THREAD

**Issue by tannerhallman** [stripe/stripe-cli#813]
_The more information we have the easier it is for us to help. Feel free to remove any sections that might not apply_

### Issue
1.7.9 exits out with no change in the config or docker-compose file. I tried all versions prior and they worked with the only change being the image version in the docker-compose file.

### Expected Behavior
Version runs fine.

### Steps to reproduce

```
version: "3.5"
services:
  stripe-cli:
    image: stripe/stripe-cli:v1.7.9
    container_name: stripe-cli-test
    build: ./
    command: listen --api-key xyz --device-name macbook --forward-to app:3000/webhooks -a
```

`docker compose up`

### Traceback

```
➜  stripe-cli-docker-test docker compose up
[+] Running 1/0
 ⠿ Container stripe-cli-test  Created                                                                                                                                                                                                                              0.0s
Attaching to stripe-cli-test
stripe-cli-test  | Deprecation warning: Expected array default value for '--directory'; got "." (string).
stripe-cli-test  | This will be rejected in the future unless you explicitly pass the options `check_default_type: false` or call `allow_incompatible_default_type!` in your code
stripe-cli-test  | You can silence deprecations warning by setting the environment variable THOR_SILENCE_DEPRECATION.
stripe-cli-test  | ERROR: "listen start" was called with arguments ["--api-key", "xyz", "--device-name", "macbook", "--forward-to", "app:3000/webhooks", "-a"]
stripe-cli-test  | Usage: "listen start"
stripe-cli-test  | Deprecation warning: Thor exit with status 0 on errors. To keep this behavior, you must define `exit_on_failure?` in `Listen::CLI`
stripe-cli-test  | You can silence deprecations warning by setting the environment variable THOR_SILENCE_DEPRECATION.
stripe-cli-test exited with code 0
```
### Environment
Docker version 20.10.12, build e91ed57
